
development:
  adapter: postgresql
  database: sample_app_db_dev
  host: localhost
  username: rodrigolenzi

test:
  adapter: postgresql
  database: sample_app_db_test
  host: localhost
  username: rodrigolenzi